[project]
name = "fantasy"
version = "0.1.0"
description = "Test out UV"
requires-python = ">=3.12,<3.15"
authors = [
    { name = "p14s", email = "tsangernest@hotmail.com" },
]
dependencies = [
    "aiomysql>=0.3.2",
    "aiosqlite>=0.22.1",
    "fastapi>=0.141.1",
    "ollama>=0.6.2",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "psycopg[binary,pool]>=3.3.5",
    "pydantic-settings>=2.15.0",
    "sqlmodel>=0.0.42",
    "uvicorn[standard]>=0.52.4",
]

[dependency-groups]
    dev = [
        "black>=26.5.1",
        "httpx>=0.28.1",
        "invoke>=3.0.3",
        "isort>=9.0.1",
        "pdbpp>=0.12.1",
        "polyfactory>=3.3.0",
        "pytest-repeat>=0.9.4",
        "pytest-xdist>=3.8.0",
    ]

[project.scripts]
fantasy = "fantasy:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src"
module-root = ""

